[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Aligning Big Brains and Atlases - ABBA"
authors = [{name = "BIOP - EPFL", email = ""}]
dynamic = ["version", "description"]
